// NTC thermistor table (int16_t format)
// Generated by update_NTC_array.py

#ifndef NTC_TABLE_H
#define NTC_TABLE_H

#ifdef __cplusplus
extern "C" {
#endif

#include <stddef.h>  // for size_t
#include <stdint.h>  // for int16_t

#define NTC_TABLE_SIZE 231
#define NTC_VOLTAGE_MIN 34 /*单位 mV*/
#define NTC_VOLTAGE_MAX 3048 /*单位 mV*/
#define NTC_TEMP_MIN -3000 /*单位 0.01°C*/
#define NTC_TEMP_MAX 20000 /*单位 0.01°C*/

extern const int16_t ntc_table[NTC_TABLE_SIZE][2];

#ifdef __cplusplus
}
#endif

#endif // NTC_TABLE_H
